### PR TITLE
Tinydb and IP/vote fix

### PR DESCRIPTION
**Pull request by JealousEntrepreneur**
Replacing CSV file with a file oriented Tinydb database. Replacing Client submitted IP with real request ip to fix spoofing. And stricter test on vote submit, so no arbitrary data can be submitted.

### CODE REVIEW

**Review by hsauers5 — COMMENTED** [review]
Have you used the Reddit OAUTH API before? I'm speaking with a mod and that was a major suggestion, but I haven't worked with it. This may render the IP collection somewhat redundant, but thanks for the fixes. 

Is there a particular reason to force a redirect from /results to / opposed to just the other way around? I don't have anything against a user viewing the results without voting personally, but I'd like to hear your thoughts.

**Comment by JealousEntrepreneur** [comment]
OAuth isn't difficult. I implemented that for google/facebook/twitter/etc. before. That would indeed solve most of the spam problem. The question is what are the release question like?
E.g. ala facebook: Are you willing to share xxx email + xxx and so on  if someone wants to use it.
Or is it somewhat seemless?

The ip thing is now easily replaceable with every other method because it's not on the client anymore, so the fixes are worth it;)

The redirect was because most people, myself included, just keep the tab open and refresh on the next day, so they aren't prompted to vote again and don't think about it because you didn't ask them. 
It's just a binary question + the more data the better for all right?

**Comment by JealousEntrepreneur** [comment]
p.s.: it redirects also from / to /results if someone already voted that day.

**Comment by hsauers5** [comment]
Ok, I agree with your reasoning for the redirects. Thanks for clarifying...
I've done OAUTH for FB/Google/Etc and will be looking into Reddit soon.

**Comment by JealousEntrepreneur** [comment]
...here, if you didn't found it by now: https://github.com/reddit-archive/reddit/wiki/oauth2-python-example

If you want to do it all by yourself and learn from your own mistakes in the process it's ok, i did the same thing 7 years ago, just tell me to f**k of and that's it. I have a business to run and the only thing that keeps me to do anything for this, or other things i don't get paid for, is if I'm enjoying it or it's a hard problem.

**Comment by hsauers5** [comment]
No, I really appreciate it. It's a bit tricky to manage alone.

I did have to roll a few things back due to issues with the convert.py and
the load balancer it's behind, but it should be at least functional now.

**Comment by JealousEntrepreneur** [comment]
why do you use a loadbalancer for a file based "database"? If you have more than 1 process/thread writing to the file it could easily destroy the csv format and the website would be down.

I would recommend that you put the table back, but under the graphic instead of above.
The people who voted want to see how other voted now and not wait til tomorrow. They want to trade on the sentiment.

**Comment by JealousEntrepreneur** [comment]
also what version of python are you using? i have to decode the urllib.request after the read because it's binary in 3.5 and needs to be decoded to string before the json load.

**Comment by hsauers5** [comment]
Only one thread... Load balancer is for SSL mostly. I use Python 3.7.

**Pull request merged**
